### ISSUE TITLE
Sublime Text 3 support

### ISSUE THREAD

**Issue by aziz** [atombender/sublime_text_alternative_autocompletion#17]
I'm getting this error in ST3: 

```
Traceback (most recent call last):
  File "/Applications/Sublime Text 3.app/Contents/MacOS/sublime_plugin.py", line 399, in run_
    return self.run(edit)
  File "/Users/allen/Library/Application Support/Sublime Text 3/Packages/Alternative Autocompletion/alternative_autocomplete.py", line 38, in run
    self.view.substr(sublime.Region(0, self.view.size())), cycle, default)
  File "/Users/allen/Library/Application Support/Sublime Text 3/Packages/Alternative Autocompletion/alternative_autocomplete.py", line 52, in insert_completion
    self.candidates = self.find_candidates(prefix, position, text)
  File "/Users/allen/Library/Application Support/Sublime Text 3/Packages/Alternative Autocompletion/alternative_autocomplete.py", line 81, in find_candidates
    candidates.sort(lambda a, b: cmp(a.distance, b.distance))
TypeError: must use keyword argument for key function
```

**Comment by doz** [comment]
@alexstaubo many thanks for the plugin, I can't live without it! That's why I updated the code to support Sublime Text 3 (https://github.com/doz/sublime_text_alternative_autocompletion/tree/ST3). I'm not into sublime text api and I'm not even python developer, but it works for me. Would be great if you check it and move to your repo for others to use.

**Comment by atombender** [comment]
Thanks, guys. I have integrated the fix from @doz. Your code looks fine, by the way, but I decided to make a small change to it. You should use a pull request the next time. :-)

**Comment by aziz** [comment]
Although you mentioned it's working on ST3 in the readme, it can not be installed on ST3 because on the Package Control website it's labeled as a ST2 only plugin. 
You should go and update package control repository to make it available in ST3.

**Comment by atombender** [comment]
Good call. Done.
